const tyneBridgeHarriersTheme = <String, dynamic>{
  'name': 'Tyne Bridge Harriers',
  'colors': {
    'primary': '#050505',
    'onPrimary': '#FFFFFF',
    'primaryContainer': '#E8E8E8',
    'onPrimaryContainer': '#050505',
    'secondary': '#676767',
    'onSecondary': '#FFFFFF',
    'secondaryContainer': '#F1F1F1',
    'onSecondaryContainer': '#202020',
    'tertiary': '#9C9C9C',
    'onTertiary': '#050505',
    'tertiaryContainer': '#F7F7F7',
    'onTertiaryContainer': '#202020',
    'background': '#FFFFFF',
    'onBackground': '#111111',
    'surface': '#FFFFFF',
    'onSurface': '#111111',
    'surfaceVariant': '#F5F5F5',
    'onSurfaceVariant': '#494949',
    'outline': '#CFCFCF',
    'outlineVariant': '#E7E7E7',
    'error': '#B3261E',
    'onError': '#FFFFFF',
    'success': '#1D7A46',
    'warning': '#B7791F',
    'inverseSurface': '#111111',
    'inverseOnSurface': '#FFFFFF',
    'inversePrimary': '#FFFFFF',
  },
  'buttons': {
    'elevated': {
      'backgroundColor': '#050505',
      'foregroundColor': '#FFFFFF',
      'disabledBackgroundColor': '#E7E7E7',
      'disabledForegroundColor': '#777777',
    },
    'filled': {
      'backgroundColor': '#050505',
      'foregroundColor': '#FFFFFF',
      'disabledBackgroundColor': '#E7E7E7',
      'disabledForegroundColor': '#777777',
    },
    'outlined': {
      'backgroundColor': '#FFFFFF',
      'foregroundColor': '#050505',
      'borderColor': '#050505',
      'disabledForegroundColor': '#777777',
      'disabledBorderColor': '#D7D7D7',
    },
    'text': {
      'foregroundColor': '#050505',
      'disabledForegroundColor': '#777777',
    },
    'icon': {
      'foregroundColor': '#050505',
      'disabledForegroundColor': '#777777',
    },
  },
  'typography': {'fontFamily': ''},
  'shape': {'borderRadius': 0.0},
  'spacing': {'edgePadding': 28.0},
};

const heatonHarriersTheme = <String, dynamic>{
  'name': 'Heaton Harriers',
  'colors': {
    'primary': '#00A676',
    'onPrimary': '#04110D',
    'primaryContainer': '#B9FFE4',
    'onPrimaryContainer': '#04110D',
    'secondary': '#F7C948',
    'onSecondary': '#111111',
    'secondaryContainer': '#302A12',
    'onSecondaryContainer': '#FFE79B',
    'tertiary': '#3DDCFF',
    'onTertiary': '#04110D',
    'tertiaryContainer': '#05323A',
    'onTertiaryContainer': '#B7F4FF',
    'background': '#050806',
    'onBackground': '#F7FFF9',
    'surface': '#101612',
    'onSurface': '#F7FFF9',
    'surfaceVariant': '#18231D',
    'onSurfaceVariant': '#CDE8D8',
    'outline': '#37D399',
    'outlineVariant': '#254634',
    'error': '#FF6B6B',
    'onError': '#111111',
    'success': '#00A676',
    'warning': '#F7C948',
    'inverseSurface': '#F7FFF9',
    'inverseOnSurface': '#050806',
    'inversePrimary': '#005A3F',
  },
  'buttons': {
    'elevated': {
      'backgroundColor': '#00A676',
      'foregroundColor': '#04110D',
      'disabledBackgroundColor': '#203128',
      'disabledForegroundColor': '#7F9B8C',
    },
    'filled': {
      'backgroundColor': '#00A676',
      'foregroundColor': '#04110D',
      'disabledBackgroundColor': '#203128',
      'disabledForegroundColor': '#7F9B8C',
    },
    'outlined': {
      'backgroundColor': '#101612',
      'foregroundColor': '#F7FFF9',
      'borderColor': '#37D399',
      'disabledForegroundColor': '#7F9B8C',
      'disabledBorderColor': '#254634',
    },
    'text': {
      'foregroundColor': '#00A676',
      'disabledForegroundColor': '#7F9B8C',
    },
    'icon': {
      'foregroundColor': '#F7FFF9',
      'disabledForegroundColor': '#7F9B8C',
    },
  },
  'typography': {'fontFamily': ''},
  'shape': {'borderRadius': 0.0},
  'spacing': {'edgePadding': 14.0},
};

const claremontTheme = <String, dynamic>{
  'name': 'Claremont Road Runners',
  'colors': {
    'primary': '#B45B37',
    'onPrimary': '#FFFFFF',
    'primaryContainer': '#FFE1D2',
    'onPrimaryContainer': '#432013',
    'secondary': '#2C7A7B',
    'onSecondary': '#FFFFFF',
    'secondaryContainer': '#D5F2EF',
    'onSecondaryContainer': '#103938',
    'tertiary': '#856404',
    'onTertiary': '#FFFFFF',
    'tertiaryContainer': '#FFE9A6',
    'onTertiaryContainer': '#3A2A00',
    'background': '#FFF8F2',
    'onBackground': '#251915',
    'surface': '#FFFDF9',
    'onSurface': '#251915',
    'surfaceVariant': '#F7E7DA',
    'onSurfaceVariant': '#62524A',
    'outline': '#E4C3B0',
    'outlineVariant': '#F0DCD0',
    'error': '#B3261E',
    'onError': '#FFFFFF',
    'success': '#2F855A',
    'warning': '#B7791F',
    'inverseSurface': '#251915',
    'inverseOnSurface': '#FFF8F2',
    'inversePrimary': '#FFD3BC',
  },
  'buttons': {
    'elevated': {
      'backgroundColor': '#B45B37',
      'foregroundColor': '#FFFFFF',
      'disabledBackgroundColor': '#EBD9CF',
      'disabledForegroundColor': '#8A7266',
    },
    'filled': {
      'backgroundColor': '#B45B37',
      'foregroundColor': '#FFFFFF',
      'disabledBackgroundColor': '#EBD9CF',
      'disabledForegroundColor': '#8A7266',
    },
    'outlined': {
      'backgroundColor': '#FFFDF9',
      'foregroundColor': '#B45B37',
      'borderColor': '#D49A7E',
      'disabledForegroundColor': '#8A7266',
      'disabledBorderColor': '#EBD9CF',
    },
    'text': {
      'foregroundColor': '#B45B37',
      'disabledForegroundColor': '#8A7266',
    },
    'icon': {
      'foregroundColor': '#B45B37',
      'disabledForegroundColor': '#8A7266',
    },
  },
  'typography': {'fontFamily': ''},
  'shape': {'borderRadius': 16.0},
  'spacing': {'edgePadding': 20.0},
};

const mockClubThemes = <Map<String, dynamic>>[
  tyneBridgeHarriersTheme,
  heatonHarriersTheme,
  claremontTheme,
];
